import constants from "@/services/constants";

export const styles = {
  boxContainer: {
    width: "100%",
    height: "520px",
    minHeight: "520px",
    border: "1px solid #EBEEF3",
    borderRadius: "20px",
    background: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
  },
  tabsItemContainer: {
    // border: "1px solid #D6D9E1",
    display: "flex",
    justifyContent: "start",
    width: "fit-content",
    gap: "24px",
    borderRadius: "12px",
    padding: "8px",
    fontWeight: 700,
    backgroundColor: constants.colors.light_grey,
    flexWrap: "wrap",
  },
  boxData: {
    padding: "20px",
    borderRadius: "20px",
    background: "#FFFFFF",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  dataSpaceBetween: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "row",
    },
    gap: {
      xs: "5px",
      sm: "0px",
    },
  },
  popupContainer: {
    border: "1px solid #EBEEF3",
    borderRadius: "12px",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    background: "#fff",
    width: "100%",
  },
  popupBtnsContainer: {
    mt: 3,
    display: "flex",
    justifyContent: "space-between",
    gap: { xs: "16px", md: "24px" },
    width: "100%",
    flexWrap: { xs: "wrap", md: "nowrap" },
    flexDirection: { xs: "column-reverse", md: "row" },
  },
  rowBox: {
    borderRadius: "12px",
    padding: "16px",
    background: "#fff",
    mb: "2px",
    gap: {
      xs: "24px",
      sm: "0px",
    },
    display: "flex",
    flexDirection: {
      xs: "column",
      sm: "row",
    },
  },
  deleteBtn: {
    background: "#D32F2F",
    color: "#fff",
    fontWeight: 700,
    border: "1px solid #D6D9E1",
    "&:hover": {
      background: "#D32F2F",
      color: "#fff",
      boxShadow: "none",
    },
  },
  detailsBtnTable: {
    borderRadius: "12px",
    border: `1px solid ${constants.colors.main}`,
    padding: "14px",
    // fontSize: "0.8rem",
    fontWeight: 700,
    color: constants.colors.main,
    cursor: "pointer",
    py: "8px",
  },
  boxGrid: {
    borderRadius: "12px",
    padding: "16px",
    mb: "2px",
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "1fr 1fr",
      md: "1fr 1fr 1fr 1fr",
    },
    gap: "16px",
  },
  tableActionRow: {
    display: "flex",
    gap: "24px",
    alignItems: "center",
    justifyContent: "end",
    ml: 2,
  },
};
